### ISSUE TITLE
throw new Error('Can't set headers after they are sent.');

### ISSUE THREAD

**Issue by IveSix** [Lullabot/react_form#2]
i configure my mail, but when i try to submit this is the error in console 

_http_outgoing.js:346
    throw new Error('Can\'t set headers after they are sent.');
    ^

Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:346:11)

**Comment by juampynr** [comment]
Have a look at this snippet: https://github.com/Lullabot/react_form/blob/master/server.js#L37-L54

**Comment by IveSix** [comment]
yes, this is my configuration  https://jsfiddle.net/9rjLg7f4/1/  whats' wrong?

**Comment by juampynr** [comment]
I am sorry, but I don't know what's wrong with it.

**Comment by IveSix** [comment]
ok, because the configuration it's ok? 

with this  i receive : ReferenceError: body is not defined

`server.send({
    'text': body,
    'from': req.body.email,
    'to': 'miamail@gmail.com',
    'reply-to': req.body.email,
    'subject': 'Tell us about your project: '
  }, function(error) {
    if (error) {
      return res.send({status: 'KO'});
    } else {
      return res.send({status: 'OK'});
    }
  });`
